spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/crm?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
server:
  servlet:
    context-path: /crm
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.alexey.LoggerTest: debug
mybatis:
  type-aliases-package: net.dhg.crm.entity
  mapper-locations: classpath:mapper/*Mapper.xml
person:
  name: ${random.uuid}
  age: ${random.int}
  haPPy: true
  birth: 2010/12/01
  map: {k1: value1,k2: value2}
  list:
    - ${person.apple:good}code #这是一个相当于 ((person.apple).isExist?person.apple:good).concat("code")
    - girl
    - music
  dog:
    name: ${person.name}`s orange
    age: 12
apple:
  name: 630909931@qq.com