spring:
#数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/crm?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#模板引擎
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
#国际化配置,配置信息的url是要配的
  messages:
    basename: i18n.login
  #mvc配置
  mvc:
    date-format: yyyy-MM-dd



#对象关系映射框架
mybatis:
  type-aliases-package: net.dhg.crm.entity
  mapper-locations: classpath:mapper/*Mapper.xml

#是否查看启用/未启用的配置类
debug: false









---
spring:
  profiles: prod
  http:
    encoding:
      charset: utf-8
  thymeleaf:
    cache: false
  mvc:
    #自定义格式化器配置
    date-format: yyyy-MM-dd



---
spring:
  thymeleaf:
    cache: false
  profiles: dev


  #logging:
  #  pattern:
  #    console: "%d - %msg%n"
  ##  path: /var/log/tomcat/
  #  file: /var/log/tomcat/sell.log
  #  level:
  #    com.alexey.LoggerTest: debug